#ifndef ADVANCED_DBMS_IMPLEMENTATION_TEST_QUERY_EXECUTION_H
#define ADVANCED_DBMS_IMPLEMENTATION_TEST_QUERY_EXECUTION_H

#include "test_support_functions.h"

void check_filter_relation(void);


#endif //ADVANCED_DBMS_IMPLEMENTATION_TEST_QUERY_EXECUTION_H
