#ifndef ADVANCED_DBMS_IMPLEMENTATION_TEST_QUERY_PARSING_H
#define ADVANCED_DBMS_IMPLEMENTATION_TEST_QUERY_PARSING_H

#include "test_radix_hash_join.h"

void check_Query_Parsing(void);


#endif //ADVANCED_DBMS_IMPLEMENTATION_TEST_QUERY_PARSING_H
